CREATE TABLE `FREQUENTATORE` (
    `CF` VARCHAR(255) PRIMARY KEY,
    `Nome` VARCHAR(255),
    `Cognome` VARCHAR(255),
    `DataNascita` DATE,
    `Email` VARCHAR(255),
    `Telefono` VARCHAR(255),
    `Indirizzo` VARCHAR(255)
);

CREATE TABLE `CERTIFICATO_MEDICO` (
    `ID_Certificato` INT PRIMARY KEY AUTO_INCREMENT,
    `DataRilascio` DATE,
    `DataScadenza` DATE,
    `TipoSport` VARCHAR(255),
    `CF_Frequentatore` VARCHAR(255)
);

CREATE TABLE `TIPO_ABBONAMENTO` (
    `ID_Tipo` INT PRIMARY KEY AUTO_INCREMENT,
    `Nome` VARCHAR(255),
    `Durata_Mesi` INT,
    `Prezzo` DECIMAL
);

CREATE TABLE `ABBONAMENTO` (
    `ID_Abbonamento` INT PRIMARY KEY AUTO_INCREMENT,
    `DataInizio` DATE,
    `DataScadenza` DATE,
    `Stato` VARCHAR(255),
    `CF_Frequentatore` VARCHAR(255),
    `ID_Tipo` INT
);

CREATE TABLE `EDIFICIO` (
    `ID_Edificio` CHAR PRIMARY KEY,
    `Descrizione` VARCHAR(255)
);

CREATE TABLE `SALA` (
    `ID_Sala` INT PRIMARY KEY AUTO_INCREMENT,
    `Nome` VARCHAR(255),
    `Capienza` INT,
    `ID_Edificio` CHAR
);

CREATE TABLE `ACCESSO` (
    `ID_Accesso` INT PRIMARY KEY AUTO_INCREMENT,
    `DataOra` DATETIME,
    `Tipo` VARCHAR(255),
    `CF_Frequentatore` VARCHAR(255),
    `ID_Edificio` CHAR
);

CREATE TABLE `ISTRUTTORE` (
    `ID_Istruttore` INT PRIMARY KEY AUTO_INCREMENT,
    `Nome` VARCHAR(255),
    `Cognome` VARCHAR(255),
    `Specializzazione` VARCHAR(255),
    `Email` VARCHAR(255)
);

CREATE TABLE `CORSO` (
    `ID_Corso` INT PRIMARY KEY AUTO_INCREMENT,
    `Nome` VARCHAR(255),
    `Disciplina` VARCHAR(255),
    `MaxPartecipanti` INT
);

CREATE TABLE `LEZIONE` (
    `ID_Lezione` INT PRIMARY KEY AUTO_INCREMENT,
    `DataOra` DATETIME,
    `Durata_Minuti` INT,
    `ID_Corso` INT,
    `ID_Sala` INT,
    `ID_Istruttore` INT
);

CREATE TABLE `PRENOTAZIONE` (
    `ID_Prenotazione` INT PRIMARY KEY AUTO_INCREMENT,
    `DataPrenotazione` DATETIME,
    `Stato` VARCHAR(255),
    `CF_Frequentatore` VARCHAR(255),
    `ID_Lezione` INT
);

ALTER TABLE `CERTIFICATO_MEDICO`
    ADD FOREIGN KEY (`CF_Frequentatore`) REFERENCES `FREQUENTATORE` (`CF`);

ALTER TABLE `ABBONAMENTO`
    ADD FOREIGN KEY (`CF_Frequentatore`) REFERENCES `FREQUENTATORE` (`CF`);

ALTER TABLE `ABBONAMENTO`
    ADD FOREIGN KEY (`ID_Tipo`) REFERENCES `TIPO_ABBONAMENTO` (`ID_Tipo`);

ALTER TABLE `SALA`
    ADD FOREIGN KEY (`ID_Edificio`) REFERENCES `EDIFICIO` (`ID_Edificio`);

ALTER TABLE `ACCESSO`
    ADD FOREIGN KEY (`CF_Frequentatore`) REFERENCES `FREQUENTATORE` (`CF`);

ALTER TABLE `ACCESSO`
    ADD FOREIGN KEY (`ID_Edificio`) REFERENCES `EDIFICIO` (`ID_Edificio`);

ALTER TABLE `LEZIONE`
    ADD FOREIGN KEY (`ID_Corso`) REFERENCES `CORSO` (`ID_Corso`);

ALTER TABLE `LEZIONE`
    ADD FOREIGN KEY (`ID_Sala`) REFERENCES `SALA` (`ID_Sala`);

ALTER TABLE `LEZIONE`
    ADD FOREIGN KEY (`ID_Istruttore`) REFERENCES `ISTRUTTORE` (`ID_Istruttore`);

ALTER TABLE `PRENOTAZIONE`
    ADD FOREIGN KEY (`CF_Frequentatore`) REFERENCES `FREQUENTATORE` (`CF`);

ALTER TABLE `PRENOTAZIONE`
    ADD FOREIGN KEY (`ID_Lezione`) REFERENCES `LEZIONE` (`ID_Lezione`);
